config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "babies#index"
  resources :babies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/baby.rb
class Baby < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :gender
  belongs_to :user
  has_one :hospital, dependent: :destroy
  has_one_attached :image

  with_options presence: true do
    validates :name
    validates :gender_id, numericality: { other_than: 1, message: "can't be blank" }
    validates :birthday
  end
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '男の子' },
    { id: 3, name: '女の子' }
  ]

  include ActiveHash::Associations
  has_many :babies
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  belongs_to :baby

  with_options presence: true do
    validates :hospitalname, :week, :phone
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :babies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]  # 環境変数を読み込む記述に変更
    end
  end
end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @baby = Baby.all
  end

  def new
    @baby = Baby.new
  end

  def create
    @baby = Baby.create(baby_params)
    Hospital.create(hospital_params)
    if @baby.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @baby = Baby.find(params[:id])
    @babybirth = @baby.birthday
    @hospital = Hospital.where(baby_id: @baby).first
  end

  def edit
    @baby = Baby.find(params[:id])
    @hospital = Hospital.where(baby_id: @baby).first
  end

  def update
    @baby = Baby.find(params[:id])
    @hospital = Hospital.where(baby_id: @baby).first
    if @baby.update(baby_params) && @hospital.update(hospital_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    baby = Baby.find(params[:id])
    if user_signed_in? && current_user.id == baby.user_id
      baby.destroy
      redirect_to root_path
    end
  end

  private

  def baby_params
    params.permit(:name, :gender_id, :birthday, :image).merge(user_id: current_user.id)
  end

  def hospital_params
    params.permit(:hospitalname, :week, :phone, :mapurl).merge(baby_id: @baby.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/babies_helper.rb
module BabiesHelper
end

app/views/babies/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
      <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/babies/_footer.html.erb
<footer>
  <% if user_signed_in? %>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"logout" %>
  <% end %>
</footer>

app/views/babies/_header.html.erb
<header>
  <div class="header">
    <div class="header-logo">
      <%= link_to image_tag("IMG_0006.PNG"), root_path, class:"logo" %>
    </div>
    <div class="header-parts">
      <% if user_signed_in? %>
        <%= link_to "New Baby", new_baby_path, class:"header-part" %>
      <% else %>
        <%= link_to "新規登録", new_user_registration_path, class:"header-part" %>
        <%= link_to "ログイン", new_user_session_path, class:"header-part" %>
      <% end %>
    </div>
  </div >
</header>

app/views/babies/edit.html.erb
<%= render "babies/header" %>
<main>
  <div class="main">
    <div class="e-contents">
      <div>
        <h1>子どもの編集ページ</h1>
      </div>
      <div class="e-form">
        <%= form_with model:@baby, local: true do |f| %>
          <%#<%= render 'error_messages', model: f.object %>
          <div class="formwrapper">
            <div class="babyinfo-wrapper">
              <div clsss="image-wrapper">
                <p>画像</p>
                <p><%= f.file_field :image, id:"baby-image" %></p>
              </div>
              <div class="name-wrapper">
                <p>名前</p>
                <%= f.text_area :name, class:"baby-text", id:"baby-name", placeholder:"おなまえ" %>
              </div>
              <div class="gender-wrapper">
                <p>性別</p>
                <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:"gender-select"}) %>
              </div>
              <div class="birthday-wrapper">
                <p>生年月日</p>
                <div class='input-birth-wrap'>
                      <%= raw sprintf(
                                  f.date_select(
                                    :birthday,
                                    class:'select-birth',
                                    id:"birth-date",
                                    use_month_numbers: true,
                                    prompt:'--',
                                    start_year: 2015,
                                    end_year: (Time.now.year + 1),
                                    date_separator: '%s'),
                                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
                </div>
              </div>
            </div>
            <div class="hospital-wrapper">
              <div>
                <p>病院名</p>
                <p><%= f.text_area :hospitalname, class:"baby-text", id:"baby-name", placeholder:"例）ますなが医院" %></p>
              </div>
              <div>
                <p>休診日</p>
                <p><%= f.text_area :week, class:"baby-text", id:"baby-name", placeholder:"例）水終日/土の午後" %></p>
              </div>
              <div>
                <p>電話番号</p>
                <p><%= f.text_area :phone, class:"baby-text", id:"baby-name", placeholder:"例）042-1234-5678" %></p>
              </div>
            </div>
          </div>
          <div class="e-button">
            <%= f.submit "登録" ,class:"e-submit" %>
            <%= link_to "戻る", root_path, class:"e-link" %>
            <%= link_to "削除", baby_path(@baby), method: :delete, class:"e-delete" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>
<%= render "babies/footer"%>

app/views/babies/index.html.erb
<%= render "babies/header" %>
<main class="main">
  
  <div class="i-yourbabies">
    <p>~YOUR BABIES~</p>
  </div>
  <% if user_signed_in? %>
    <div class="i-cards-wrapper">
      <div class="i-cards">
        <% @baby.each do |baby| %>
          <div class="i-card">
            <a href="/babies/<%= baby.id %>" class="i-showlink">
              <div class="i-card-contents">
                <div class="i-baby-image">
                  <%= image_tag baby.image, class:"i-baby-image" %>
                </div>
                <div class="i-baby-info">
                  <p>おなまえ：<%= baby.name %></p>
                  <p>せいべつ：<%= baby.gender.name %></p>
                  <p>おたんじょうび：<%= baby.birthday %></p>
                </div>
              </div>
            </a>
            <div class="i-baby-edit">
              <div class="i-edit-button">
                <%= link_to "編集する", edit_baby_path(baby), class:"i-edit" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% else %>
      <div class="i-not-login">
        <div class="not-signin">
          <p>ログイン後に表示されます</p>
        </div>
      </div>
  <% end %>
</main>
<%= render "babies/footer"%>

app/views/babies/new.html.erb
<%= render "babies/header" %>
<main>
  <div class="main">
    <div class="n-contents">
      <div>
        <h1>子どもの新規登録</h1>
      </div>
      <div class="n-form">
        <%= form_with url: babies_path, local: true do |f| %>
          <%#<%= render 'error_messages', model: f.object %>
          <div class="formwrapper">
            <div class="babyinfo-wrapper">
              <div class="image-wrapper">
                <p>画像</p>
                <p><%= f.file_field :image, class:"baby-image2" %></p>
              </div>
              <div class="name-wrapper">
                <p>名前</p>
                <p><%= f.text_area :name, class:"baby-text", id:"baby-name", placeholder:"おなまえ" %></p>
              </div>
              <div class="gender-wrapper">
                <p>性別</p>
                <p><%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:"gender-select"}) %></p>
              </div>
              <div class="birthday-wrapper">
                <p>生年月日</p>
                <div class='input-birth-wrap'>
                      <%= raw sprintf(
                                  f.date_select(
                                    :birthday,
                                    class:'select-birth',
                                    id:"birth-date",
                                    use_month_numbers: true,
                                    prompt:'--',
                                    start_year: 2015,
                                    end_year: (Time.now.year + 1),
                                    date_separator: '%s'),
                                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
                </div>
              </div>
            </div>
            <div class="hospital-wrapper">
              <div>
                <p>病院名</p>
                <p><%= f.text_area :hospitalname, class:"baby-text", id:"baby-name", placeholder:"例）ますなが医院" %></p>
              </div>
              <div>
                <p>休診日</p>
                <p><%= f.text_area :week, class:"baby-text", id:"baby-name", placeholder:"例）水終日/土の午後" %></p>
              </div>
              <div>
                <p>電話番号</p>
                <p><%= f.text_area :phone, class:"baby-text", id:"baby-name", placeholder:"例）042-1234-5678" %></p>
              </div>
            </div>
          </div>
          <div class="n-button">
            <%= f.submit "登録" ,class:"n-submit" %>
            <%= link_to "戻る", root_path, class:"n-link" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>
<%= render "babies/footer"%>

app/views/babies/show.html.erb
<%= render "babies/header" %>
<main class="main">
  <div class="show-wrapper">
    <div class="s-baby-data">
      <div class="s-baby-card">
        <div class="s-baby-image">
          <%= image_tag @baby.image.variant(resize: '250x250'), class:"s-image" %>
        </div>
        <div class="s-baby-info">
          <p>おなまえ: <%= @baby.name %></p>
          <p>せいべつ: <%= @baby.gender.name %></p>
          <p>おたんじょうび: <%= @babybirth %></p>
        </div>
      </div>
      <div class="s-hospital">
        <span class="box-title">〜病院情報〜</span>
          <p>病院名　：<%= @hospital.hospitalname %></p>
          <p>休診日　：<%= @hospital.week %></p>
          <p>電話番号：<%= @hospital.phone %></p>
      </div>
<%
=begin
      <div class="s-memo">
        <span class="box-title">〜MEMO〜</span>
        <p>ここに文章が入ります</p>
      </div>
=end %>
    </div>
    <div class="s-table">
      <table>
      <tbody>
        <tr>
          <th class="fixed01 color2 z3">
            <p></p>
          </th>
          <th class="fixed02 color2 z2">
            <p>0ヶ月</p>
            <p><%= "#{@baby.birthday}〜　" %></p>
          </th>
          <th class="fixed02 color2 z2">
            <p>1ヶ月</p>
            <p><%= "#{@baby.birthday>>1}〜　" %></p>
          </th>
          <th class="fixed02 color2 z2">
            <p>2ヶ月</p>
            <p><%= "#{@baby.birthday>>2}〜　" %></p>
          </th>
          <th class="fixed02 color2 z2">
            <p>3ヶ月</p>
            <p><%= "#{@baby.birthday>>3}〜　" %></p>
          </th>
          <th class="fixed02 color2 z2">
            <p>4ヶ月</p>
            <p><%= "#{@baby.birthday>>4}〜　" %></p>
          </th>
          <th class="fixed02 color2 z2">
            <p>5ヶ月</p>
            <p><%= "#{@baby.birthday>>5}〜　" %></p>
          </th>
          <th class="fixed02 color2 z2">
            <p>6ヶ月</p>
            <p><%= "#{@baby.birthday>>6}〜　" %></p>
          </th>
          <th class="fixed02 color2 z2">
            <p>7ヶ月</p>
            <p><%= "#{@baby.birthday>>7}〜　" %></p>
          </th>
          <th class="fixed02 color2 z2">
            <p>8ヶ月</p>
            <p><%= "#{@baby.birthday>>8}〜　" %></p>
          </th>
          <th class="fixed02 color2 z2">
            <p>9ヶ月</p>
            <p><%= "#{@baby.birthday>>9}〜　" %></p>
          </th>
          <th class="fixed02 color2 z2">
            <p>10ヶ月</p>
            <p><%= "#{@baby.birthday>>10}〜　" %></p>
          </th>
          <th class="fixed02 color2 z2">
            <p>11ヶ月</p>
            <p><%= "#{@baby.birthday>>11}〜　" %></p>
          </th>
          <th class="fixed02 color2 z2">
            <p>12ヶ月</p>
            <p><%= "#{@baby.birthday>>12}〜　" %></p>
          </th>
          <th class="fixed02 color2 z2">
            <p>15ヶ月</p>
            <p><%= "#{@baby.birthday>>15}〜　" %></p>
          </th>
          <th class="fixed02 color2 z2">
            <p>18ヶ月</p>
            <p><%= "#{@baby.birthday>>18}〜　" %></p>
          </th>
          <th class="fixed02 color2 z2">
            <p>21ヶ月</p>
            <p><%= "#{@baby.birthday>>21}〜　" %></p>
          </th>
          <th class="fixed02 color2 z2">
            <p>24ヶ月</p>
            <p><%= "#{@baby.birthday>>24}〜　" %></p>
          </th>
          <th class="fixed02 color2 z2">
            <p>36ヶ月</p>
            <p><%= "#{@baby.birthday>>36}〜　" %></p>
          </th>
          <th class="fixed02 color2 z2">
            <p>48ヶ月</p>
            <p><%= "#{@baby.birthday>>48}〜　" %></p>
          </th>
          <th class="fixed02 color2 z2">
            <p>60ヶ月</p>
            <p><%= "#{@baby.birthday>>60}〜　" %></p>
          </th>
        </tr>
        <tr>
          <th class="fixed02 color1">ヒブ</th>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1">①</td>
          <td class="color1">②</td>
          <td class="color1">③</td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1">④</td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
        </tr>
        <tr>
          <th class="fixed02 color2">小児肺炎球菌</th>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2">①</td>
          <td class="color2">②</td>
          <td class="color2">③</td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2">④</td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
        </tr>
        <tr>
          <th class="fixed02 color1">ロタウイルス（３回接種）</th>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1">①</td>
          <td class="color1">②</td>
          <td class="color1">③</td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
        </tr>
        <tr>
          <th class="fixed02 color2">四種混合</th>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2">①</td>
          <td class="color2">②</td>
          <td class="color2">③</td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2">④</td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
        </tr>
        <tr>
          <th class="fixed02 color1">B型肝炎</th>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1">①</td>
          <td class="color1">②</td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1">③</td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
        </tr>
        <tr>
          <th class="fixed02 color2">BCG</th>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2">①</td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
        </tr>
        <tr>
          <th class="fixed02 color1">麻疹風疹混合</th>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1">①</td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
        </tr>
        <tr>
          <th class="fixed02 color2">水疱瘡</th>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2">①</td>
          <td class="color2">②</td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
        </tr>
        <tr>
          <th class="fixed02 color1">日本脳炎</th>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1"></td>
          <td class="color1">①②</td>
          <td class="color1">③</td>
          <td class="color1">※９歳で４回目</td>
        </tr>
        <tr>
          <th class="fixed02 color2">おたふく風邪</th>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2">①</td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2"></td>
          <td class="color2">②</td>
        </tr>
      </tbody>
      </table>
    </div>
  </div>
</main>
<%= render "babies/footer"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SUKU-SUKU</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>